import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* General Margins: md:ml-24 md:mr-24 md:mt-4 */}
      <body className="md:mt-4">{children}</body>
    </html>
  );
}
